# Datenquellen

## Kategorien

### Datenbanksysteme

* Halten Geschäftsdaten in einer konsistenten Form
* Selektion der Daten aus der Datenbank z.B. mit SQL
* Viele andere Datenbanksysteme existieren mit Abfragesprachen wie N1QL, gesprochen "Nickel"

### REST-Schnittstellen

* Zugriff auf einen sogenannten RESTful WebService
  * Heute quasi die absolute Majorität der Daten
  * Geschäftsdaten, Log-Dateien, Metrik-Informationen zur Überwachung, Sensoren, ...

  * Beispiel

In [ ]:
import pandas as pd
pd.read_json('people.json')

In [ ]:
pd.read_json('http://javacream.eu:8080/people')

In [4]:
pd.read_csv('https://raw.githubusercontent.com/lawlesst/vivo-sample-data/refs/heads/master/data/csv/people.csv')

,person_ID,name,first,last,middle,email,phone,fax,title
0,3130,"Burks, Rosella",Rosella,Burks,NaN,BurksR@univ.edu,963.555.1253,963.777.4065,Professor
1,3297,"Avila, Damien",Damien,Avila,NaN,AvilaD@univ.edu,963.555.1352,963.777.7914,Professor
2,3547,"Olsen, Robin",Robin,Olsen,NaN,OlsenR@univ.edu,963.555.1378,963.777.9262,Assistant Professor
3,1538,"Moises, Edgar Estes",Edgar,Moises,Estes,MoisesE@univ.edu,963.555.2731x3565,963.777.8264,Professor
4,2941,"Brian, Heath Pruitt",Heath,Brian,Pruitt,BrianH@univ.edu,963.555.2800,963.777.7249,Associate Curator
5,2401,"Claude, Elvin Haney",Elvin,Claude,Haney,ClaudeE@univ.edu,963.555.2902,963.777.9730,Curator
6,2070,"Mosley, Edmund",Edmund,Mosley,NaN,MosleyE@univ.edu,963.555.2945,963.777.9285,Assistant Professor
7,2561,"Derek, Antoine Mccoy",Antoine,Derek,Mccoy,DerekA@univ.edu,963.555.2992,963.777.5454,Curator
8,1625,"Hawkins, Callie",Callie,Hawkins,NaN,HawkinsC@univ.edu,963.555.3350x6480,963.777.4949,Professor
9,1307,"Pate, Andrea",Andrea,Pate,NaN,PateA@univ.edu,963.555.3723,963.777.5049,Professor
10,2342,"Austin, Liz",Liz,Austin,NaN,AustinL@univ.edu,963.555.4305,963.777.6143,Assistant Professor
11,2755,"Kendrick, Reba Alford",Reba,Kendrick,Alford,KendrickR@univ.edu,963.555.4618x7744,963.777.4371,Associate Curator
12,4150,"Sims, Angelina",Angelina,Sims,NaN,SimsA@univ.edu,963.555.5278,963.777.4400,Professor
13,3544,"Mullins, Kimberly",Kimberly,Mullins,NaN,MullinsK@univ.edu,963.555.5471x1017,963.777.9783,Assistant Professor
14,2096,"Chuck, Lloyd Haney",Lloyd,Chuck,Haney,ChuckL@univ.edu,963.555.5568x2652,963.777.9290,Assistant Professor
15,1089,"Payne, Ladonna",Ladonna,Payne,NaN,PayneL@univ.edu,963.555.5639,963.777.6469,Professor
16,2948,"Baxter, Johnathan Browning",Johnathan,Baxter,Browning,BaxterJ@univ.edu,963.555.5902,963.777.8336,Research Professor
17,4539,"Weiss, Gilbert",Gilbert,Weiss,NaN,WeissG@univ.edu,963.555.5969,963.777.4975,Professor
18,2811,"Deirdre, Florence Barrera",Florence,Deirdre,Barrera,DeirdreF@univ.edu,963.555.6319,963.777.9654,Associate Curator
19,4580,"Fernando, Toby Calderon",Toby,Fernando,Calderon,FernandoT@univ.edu,963.555.6469,963.777.9864,Research Professor
20,2895,"Garrison, Patrica",Patrica,Garrison,NaN,GarrisonP@univ.edu,963.555.6760,963.777.4958,Associate Curator
21,2254,"Effie, Leila Vinson",Leila,Effie,Vinson,EffieL@univ.edu,963.555.6824,963.777.7299,Assistant Professor
22,2389,"Buckley, Rose",Rose,Buckley,NaN,BuckleyR@univ.edu,963.555.6855x5018,963.777.5233,Curator
23,1699,"Stanton, Kathie",Kathie,Stanton,NaN,StantonK@univ.edu,963.555.7095,963.777.1015,Professor
24,1567,"Banks, Shannon",Shannon,Banks,NaN,BanksS@univ.edu,963.555.7198,963.777.6979,Professor
25,3066,"Barnes, Cleo",Cleo,Barnes,NaN,BarnesC@univ.edu,963.555.7463x7335,963.777.1583,Research Professor
26,2426,"Brady, Nellie",Nellie,Brady,NaN,BradyN@univ.edu,963.555.7569,963.777.7218,Curator
27,2217,"Katheryn, Ruben Holt",Ruben,Katheryn,Holt,KatherynR@univ.edu,963.555.7578,963.777.3969,Assistant Professor
28,1968,"Michael, Dianne",Dianne,Michael,NaN,MichaelD@univ.edu,963.555.7592,963.777.9960,Assistant Professor
29,3012,"Grant, Adam",Adam,Grant,NaN,GrantA@univ.edu,963.555.7775,963.777.8115,Research Professor
30,1824,"Head, Kurtis",Kurtis,Head,NaN,HeadK@univ.edu,963.555.7882,963.777.6348,Professor
31,3929,"Berger, Jami",Jami,Berger,NaN,BergerJ@univ.edu,963.555.8158,963.777.5650,Research Professor
32,2682,"Earline, Jaime Fitzgerald",Jaime,Earline,Fitzgerald,EarlineJ@univ.edu,963.555.8357,963.777.4114,Associate Curator
33,3112,"Evelyn, Summer Frost",Summer,Evelyn,Frost,EvelynS@univ.edu,963.555.8895,963.777.5730,Professor
34,2303,"Quentin, Sam Hyde",Sam,Quentin,Hyde,QuentinS@univ.edu,963.555.8921,963.777.2712,Assistant Professor
35,3903,"Dunlap, Ann",Ann,Dunlap,NaN,DunlapA@univ.edu,963.555.9067,963.777.4290,Assistant Professor
36,3095,"Shields, Rich Pena",Rich,Shields,Pena,ShieldsR@univ.edu,963.555.9197,963.777.7215,Professor
37,2383,"Page, Winnie",Winnie,Page,NaN,PageW@univ.edu,963.555.9366,963.777.3202,Curator
38,2146,"Sparks, Ezra",Ezra,Sparks,NaN,SparksE@univ.edu,963.555.9390,963.777.9273,Assistant Professor
39,3958,"Kaufman, Elba",Elba,Kaufman,NaN,KaufmanE@univ.edu,963.555.9507,963.777.3298,Professor

### Idee für ein Todo

* Schritte zum Auslesen einer Datenbank-Tabelle? 
  * Welcher Datenbank-Hersteller?
    * Installation des notwendigen Treibers
    * z.B. pip install mysql-connector-python
  * Aufbauen einer Connextion mit Informationen user, password, db-name, endpoint
  * Welche Tabelle enthält die Daten?
    select * from people

In [6]:
import mysql.connector

connection = mysql.connector.connect(
    host='javacream.eu', 
    port=3406, 
    database='javacream', 
    user='user', 
    password='user'
)

pd.read_sql('select id, lastname, firstname from PEOPLE', connection)

C:\Users\raine\AppData\Local\Temp\ipykernel_7660\3153863912.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql('select id, lastname, firstname from PEOPLE', connection)

   id      lastname firstname
0   1      Sawitzki    Rainer
1   2  Musterperson    Andrea
2   3     Schneider    Hannah