# Allgemein

* Erste Näherung
    * Ein DataFrame ist nichts anderes als eine Tabelle
    * Damit ist eine Sicht auf die Daten ist eine "Liste von Listen"
* Genauer
    * Ein DataFrame besteht aus Series
    * Eine Series besteht aus einer Index-Spalte und einer Wertspalte
        * Damit ist eine Series bereits selber eine Minitabelle

In [1]:
import pandas as pd

names_list = ['Hugo', 'Hanna', 'Andrea'] # ganz normale Python-Liste
print(names_list)
names_series = pd.Series(names_list)
print(names_series)

['Hugo', 'Hanna', 'Andrea']
0      Hugo
1     Hanna
2    Andrea
dtype: object

* Series mit Werte- und Index-Liste

In [2]:
names_series = pd.Series(names_list, index= ['a', 'b', 'c'])
print(names_series)

a      Hugo
b     Hanna
c    Andrea
dtype: object

* Series aus einem Dictionary

In [3]:
names_dict= {'a': 'Hugo', 'b': 'Hannah', 'c': 'Andrea'}
names_series = pd.Series(names_dict)
names_series

a      Hugo
b    Hannah
c    Andrea
dtype: object

### Series-Operationen

* Erzeugung einer Series aus einer Tabelle / Einem Dictionary
* Neuinterpretation: Mathematische Operatoren und Series

In [29]:
names_dict= {'a': 'Hugo', 'b': 'Hannah', 'c': 'Andrea'}
names_dict2= {'a': 'Franz', 'b': 'Giselle', 'd': 'Fritz'}
l1 = [1, 2, 3]
l2 = [4, 5, 6]
print(l1 + l2)
# names_dict + names_dict2
series1 = pd.Series(l1)
series2 = pd.Series(l2)

series1 * series2

[1, 2, 3, 4, 5, 6]

0     4
1    10
2    18
dtype: int64

### Series-Methoden

In [ ]:
# series1. # Code Assist

### Von der Series zum DataFrame

In [20]:
pd.read_csv('people.csv')

     lastname  firstname  height_cm  weight_kg
0      Müller     Thomas      197.0        NaN
1     Schmidt    Michael      192.0       50.0
2   Schneider    Andreas      191.0        NaN
3     Fischer     Stefan      195.0       70.0
4       Weber  Christian      185.0       73.0
5       Meyer     Markus      183.0       67.0
6      Wagner     Daniel        NaN      116.0
7      Becker      Kevin      193.0      113.0
8      Schulz     Sascha      197.0      117.0
9    Hoffmann       Jens      193.0        NaN
10       Koch     Oliver        NaN       82.0
11      Bauer    Patrick      165.0       93.0
12    Richter        Jan        NaN        NaN
13      Klein     Tobias      168.0       63.0
14       Wolf  Sebastian      165.0        NaN
15   Schröder  Alexander      187.0       64.0
16    Neumann     Dennis        NaN       94.0
17      Braun      Frank        NaN        NaN
18    Schwarz        Tim      176.0       55.0
19     Krüger      Lukas      178.0       58.0

* Erzeugung eines DataFrames

In [25]:
data = {'name': ['Hugo', 'Hannah', 'Andrea'], 'weight': [77.7, 55.5, 66.6], 'heigth': [188, 177, 166]}
# pd.DataFrame(data, index=data['name'])
pd.DataFrame(data)

     name  weight  heigth
0    Hugo    77.7     188
1  Hannah    55.5     177
2  Andrea    66.6     166

In [33]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
series1 = pd.Series(l1)
series2 = pd.Series(l2, index=['a', 'b', 'c'])
print(series1)
df = pd.DataFrame([series1, series2])
df

0    1
1    2
2    3
dtype: int64

     0    1    2    a    b    c
0  1.0  2.0  3.0  NaN  NaN  NaN
1  NaN  NaN  NaN  4.0  5.0  6.0

* Zugriff auf Elemente

In [39]:
df['a']

0    NaN
1    4.0
Name: a, dtype: float64

In [40]:

df.loc[0]

0    1.0
1    2.0
2    3.0
a    NaN
b    NaN
c    NaN
Name: 0, dtype: float64