# Titanic-Datensatz

## Laden der einzelnen Datensätze

In [1]:
import pandas as pd

In [2]:
titanic_part1_df = pd.read_csv('titanic.csv')
titanic_part1_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
titanic_part2_incomplete_df = pd.read_csv('titanic_part2_incomplete.csv')
titanic_part2_incomplete_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q

In [4]:
titanic_part2_survival_df = pd.read_csv('titanic_part2_survival.csv')
titanic_part2_survival_df.head()

   PassengerId  Survived
0          951         0
1          952         0
2          953         0
3          954         0
4          955         0

## Mergen der unvollständigen Daten

In [6]:
titanic_part2_df = pd.merge(titanic_part2_incomplete_df, titanic_part2_survival_df, how='inner', on='PassengerId')
titanic_part2_df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,951,1,"Chaudanson, Miss. Victorine",female,36.0,0,0,PC 17608,262.3750,B61,C,0
1,952,3,"Dika, Mr. Mirko",male,17.0,0,0,349232,7.8958,NaN,S,0
2,953,2,"McCrae, Mr. Arthur Gordon",male,32.0,0,0,237216,13.5000,NaN,S,0
3,954,3,"Bjorklund, Mr. Ernst Herbert",male,18.0,0,0,347090,7.7500,NaN,S,0
4,955,3,"Bradley, Miss. Bridget Delia",female,22.0,0,0,334914,7.7250,NaN,Q,0

## Erzeugen des Gesamtdatensatzes

In [9]:
df = pd.concat([titanic_part1_df, titanic_part2_df])
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
354,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
355,1306,0,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
356,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
357,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
358,1309,1,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

## Exploration

In [10]:
df.shape

(1308, 12)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1308 entries, 0 to 358
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1308 non-null   int64
 1   Survived     1308 non-null   int64
 2   Pclass       1308 non-null   int64
 3   Name         1308 non-null   object
 4   Sex          1308 non-null   object
 5   Age          1045 non-null   float64
 6   SibSp        1308 non-null   int64
 7   Parch        1308 non-null   int64
 8   Ticket       1308 non-null   object
 9   Fare         1307 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1306 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 132.8+ KB

In [12]:
df .describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1308.000000,1308.000000,1308.000000,1045.000000,1308.000000,1308.000000,1307.000000
mean,654.819572,0.295872,2.294343,29.879110,0.499235,0.385321,33.315024
std,378.108257,0.456608,0.837929,14.420245,1.041965,0.865826,51.773651
min,1.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,327.750000,0.000000,2.000000,21.000000,0.000000,0.000000,7.895800
50%,654.500000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,982.250000,1.000000,3.000000,39.000000,1.000000,0.000000,31.275000
max,1309.000000,1.000000,3.000000,80.000000,8.000000,9.000000,512.329200

In [20]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [19]:
df['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148', 'B45', 'B36', 'A21', 'D34', 'A9', 'C31', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C55 C57', 'C116', 'F', 'A29', 'C6', 'C28',
       'C51', 'C97', 'D22', 'B10', 'E45', 'E52', 'A11', 'B11', 'C80',
       'C89', 'F E46', 'B26', 'F E57', 'A18', 'E60', 'E39 E41',
       'B52 B54 B56', 'C39', 'B24', 'D40', 'D38', 'C105'], dtype=object)

* Folgerungen (subjektiv, es ist meine Analyse)
  * Es gibt Lücken in den Datensätzen
  * PassengerID ist redundant, wir haben ja bereits den Index
  * Ticket ist im Wesentlichen ein "Zufallswert" ohne weitere Bedeutung
  * Survival ist eigentlich ein logischer Wert, 0=Tot, 1=überlebt
  * Pclass = Passenger Class hat nur die Werte 1st, 2nd, 3rd, ist kategorisch
  * Sex, Embarked = Zustiegspunkt ebenfalls eine kategorische Variable
  * Cabin hat einen interessanten Aufbau, Zeichenkette + Nummer
  * Parch /Sibsp: Anzahl der Eltern Kinder bzw. Angehörige

## Cleanup

* Lücken in den Daten werden behoben
  * Alter wird durch das mittlere Passagier-Alter ersetzt
  * Embarked 'U'
* Die Spalten PassengerID und Ticket sind unnötig
* Survival durch eine logische Spalte ersetzen oder als eine kategorische Variable definieren
* Pclass muss categorial sein
* Sex, Embarked, ebenfalls categorial machen
* Cabin wird in 2 neue Spalten zerlegt: Bereich der Titanic (Anfangsbuchstabe) und die Kabinennummer als Ganzzahl

### Löschen der überflüssigen Spalten

In [23]:
df.drop('PassengerId', axis=1, inplace=True)
df.drop('Ticket', axis=1, inplace=True)

### Setzen eines unbekannten Alters auf das Durchschnittsalter
* Erweiterung: Durchschnittsalter für Frauen und Männer getrennt

In [41]:
df.loc[(df['Sex'] == 'female') & (df['Age'].isnull())]

Empty DataFrame
Columns: [Survived, Pclass, Name, Sex, Age, SibSp, Parch, Fare, Cabin, Embarked]
Index: []

In [39]:
male_mean_age = df[df['Sex'] == 'male']['Age'].mean()
female_mean_age = df[df['Sex'] == 'female']['Age'].mean()

df.loc[(df['Sex'] == 'female') & (df['Age'].isnull()), 'Age'] = female_mean_age
df.loc[(df['Sex'] == 'male') & (df['Age'].isnull()), 'Age'] = male_mean_age

In [42]:
df

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
354,0,3,"Spector, Mr. Woolf",male,30.583075,0,0,8.0500,NaN,S
355,0,1,"Oliva y Ocana, Dona. Fermina",female,39.000000,0,0,108.9000,C105,C
356,0,3,"Saether, Mr. Simon Sivertsen",male,38.500000,0,0,7.2500,NaN,S
357,0,3,"Ware, Mr. Frederick",male,30.583075,0,0,8.0500,NaN,S
358,1,3,"Peter, Master. Michael J",male,30.583075,1,1,22.3583,NaN,C