# Ein Datensatz mit Büchern

## Einlesen der Daten

In [60]:
import pandas as pd

df = pd.read_json('https://raw.githubusercontent.com/ozlerhakan/mongodb-json-files/master/datasets/books.json', lines=True)
#df.set_index('_id', inplace=True)
df.drop(['_id', 'publishedDate', 'longDescription', 'status', 'thumbnailUrl'], inplace=True, axis=1)
df.head()

,title,isbn,pageCount,shortDescription,authors,categories
0,Unlocking Android,1933988673,416,Unlocking Android: A Developer's Guide provide...,"[W. Frank Ableson, Charlie Collins, Robi Sen]","[Open Source, Mobile]"
1,"Android in Action, Second Edition",1935182722,592,"Android in Action, Second Edition is a compreh...","[W. Frank Ableson, Robi Sen]",[Java]
2,Specification by Example,1617290084,0,NaN,[Gojko Adzic],[Software Engineering]
3,Flex 3 in Action,1933988746,576,NaN,"[Tariq Ahmed with Jon Hirschi, Faisal Abid]",[Internet]
4,Flex 4 in Action,1935182420,600,NaN,"[Tariq Ahmed, Dan Orlando, John C. Bland II, J...",[Internet]

* Hinweis
  * Die JSON-Datei enthält Book-Objekte zeilenweise, nicht in Form einer Liste
  * Deshalb ist beim Einlesen der Parameter lines=True zu setzen

## Beschreibung

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431 entries, 0 to 430
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             431 non-null    object
 1   isbn              428 non-null    object
 2   pageCount         431 non-null    int64
 3   shortDescription  160 non-null    object
 4   authors           431 non-null    object
 5   categories        431 non-null    object
dtypes: int64(1), object(5)
memory usage: 20.3+ KB

In [62]:
df.describe()

         pageCount
count   431.000000
mean    289.259861
std     260.873349
min       0.000000
25%       0.000000
50%     350.000000
75%     475.000000
max    1101.000000

## Dicke Bücher, die mehr als 800 Seiten haben

In [63]:
df[df['pageCount'] > 800]

,title,isbn,pageCount,shortDescription,authors,categories
22,Java Persistence with Hibernate,1932394885,880,"""...this book is the ultimate solution. If you...","[Christian Bauer, Gavin King]",[Java]
60,Essential Guide to Peoplesoft Development and ...,1884777929,1101,NaN,"[Tony DeLia, Galina Landres, Isidor Rivera, Pr...",[Client-Server]
68,Java Foundation Classes,1884777678,1088,NaN,"[Stephen C. Drye, William C. Wake]",[Java]
102,"Java Network Programming, Second Edition",188477749X,860,NaN,"[Merlin Hughes, Michael Shoffner, , Derek Hamner]",[Java]
126,The Awesome Power of Direct3D/DirectX,1884777473,840,The Awesome Power of Direct3D/DirectX shows yo...,[Peter J. Kovach],[Computer Graphics]
174,SQL Server MVP Deep Dives,1935182048,848,SQL Server MVP Deep Dives is organized into fi...,"[Contributions from 53 SQL Server MVPs, Edited...",[Microsoft .NET]
175,SQL Server MVP Deep Dives,9781935182047,848,SQL Server MVP Deep Dives is organized into fi...,[Contributions from 53 SQL Server MVPs; Edited...,[Microsoft .NET]
176,SQL Server MVP Deep Dives,9781935182047,848,NaN,"[Paul Nielsen, Kalen Delaney, Greg Low, Adam M...",[Microsoft .NET]
192,Silverlight 5 in Action,1617290319,925,NaN,[Pete Brown],"[Microsoft, .NET]"
214,Swing Second Edition,193011088X,912,NaN,[],"[Java, Internet]"
254,Ten Years of UserFriendly.Org,1935182129,1096,This unique collector's volume includes every ...,"[JD ""Illiad"" Frazer]",[Miscellaneous]
401,Windows Forms in Action,1932394656,950,NaN,[],[]
412,Dynamic WAP Application Development,1930110081,888,NaN,[],[]

## Die 25% der seitenstärksten Bücher

In [64]:
quantile_75 = df['pageCount'].quantile(0.75)
df[df['pageCount'] > quantile_75]

,title,isbn,pageCount,shortDescription,authors,categories
1,"Android in Action, Second Edition",1935182722,592,"Android in Action, Second Edition is a compreh...","[W. Frank Ableson, Robi Sen]",[Java]
3,Flex 3 in Action,1933988746,576,NaN,"[Tariq Ahmed with Jon Hirschi, Faisal Abid]",[Internet]
4,Flex 4 in Action,1935182420,600,NaN,"[Tariq Ahmed, Dan Orlando, John C. Bland II, J...",[Internet]
10,Flexible Rails,1933988509,592,"""Flexible Rails created a standard to which I ...",[Peter Armstrong],[Web Development]
14,Brownfield Application Development in .NET,1933988711,550,Brownfield Application Development in .Net sho...,"[Kyle Baley, Donald Belcham]",[Microsoft]
...,...,...,...,...,...,...
413,IronPython in Action,1933988339,496,NaN,[],[]
414,Art of Java Web Development,1932394060,624,NaN,[],[]
417,Struts Recipes,1932394249,520,NaN,[],[]
419,Jess in Action,1930110898,480,Jess in Action first introduces rule programmi...,[],[]
423,ASP.NET AJAX in Action,1933988142,570,NaN,[],[]

## Welche Bücher haben die Kategorie 'Python'

In [65]:
selection_vector = df['categories'].astype(str).str.contains('Python')
df[selection_vector]

,title,isbn,pageCount,shortDescription,authors,categories
34,Hello! Python,1935182080,350,Hello! Python fully covers the building blocks...,[Anthony Briggs],[Python]
41,"The Quick Python Book, Second Edition",193518220X,360,This revision of Manning's popular The Quick P...,[Naomi R. Ceder],[Python]
81,Python and Tkinter Programming,1884777813,688,NaN,[John E. Grayson],[Python]
87,The Quick Python Book,1884777740,444,NaN,"[Daryl Harms, Kenneth McDonald]",[Python]
206,wxPython in Action,1932394621,620,"""The book is easy to read and provides an appr...","[Noel Rappin, Robin Dunn]",[Python]
220,Hello World!,1933988495,432,Hello World! provides a gentle but thorough in...,"[Warren D. Sande, Carter Sande]","[Programming, Python]"

In [66]:
for index, row in df.iterrows():
    print(index, row)

0 title                                               Unlocking Android
isbn                                                       1933988673
pageCount                                                         416
shortDescription    Unlocking Android: A Developer's Guide provide...
authors                 [W. Frank Ableson, Charlie Collins, Robi Sen]
categories                                      [Open Source, Mobile]
Name: 0, dtype: object
1 title                               Android in Action, Second Edition
isbn                                                       1935182722
pageCount                                                         592
shortDescription    Android in Action, Second Edition is a compreh...
authors                                  [W. Frank Ableson, Robi Sen]
categories                                                     [Java]
Name: 1, dtype: object
2 title               Specification by Example
isbn                              1617290084
pageCount                                  0
shortDescription                         NaN
authors                        [Gojko Adzic]
categories            [Software Engineering]
Name: 2, dtype: object
3 title                                          Flex 3 in Action
isbn                                                 1933988746
pageCount                                                   576
shortDescription                                            NaN
authors             [Tariq Ahmed with Jon Hirschi, Faisal Abid]
categories                                           [Internet]
Name: 3, dtype: object
4 title                                                Flex 4 in Action
isbn                                                       1935182420
pageCount                                                         600
shortDescription                                                  NaN
authors             [Tariq Ahmed, Dan Orlando, John C. Bland II, J...
categories                                                 [Internet]
Name: 4, dtype: object
5 title               Collective Intelligence in Action
isbn                                       1933988312
pageCount                                         425
shortDescription                                  NaN
authors                                 [Satnam Alag]
categories                                 [Internet]
Name: 5, dtype: object
6 title                                        Zend Framework in Action
isbn                                                       1933988320
pageCount                                                         432
shortDescription    Zend Framework in Action is a comprehensive tu...
authors                            [Rob Allen, Nick Lo, Steven Brown]
categories                                          [Web Development]
Name: 6, dtype: object
7 title                                                    Flex on Java
isbn                                                       1933988797
pageCount                                                         265
shortDescription       A beautifully written book that is a must h...
authors                             [Bernerd Allmon, Jeremy Anderson]
categories                                                 [Internet]
Name: 7, dtype: object
8 title                                               Griffon in Action
isbn                                                       1935182234
pageCount                                                         375
shortDescription    Griffon in Action is a comprehensive tutorial ...
authors              [Andres Almiray, Danno Ferrin, , James Shingler]
categories                                                     [Java]
Name: 8, dtype: object
9 title                                                   OSGi in Depth
isbn                                                       193518217X
pageCount                                                         325
shortDescription    Enterprise OSGi shows a Java developer how to ...
authors                                   [Alexandre de Castro Alves]
categories                                                     [Java]
Name: 9, dtype: object
10 title                                                  Flexible Rails
isbn                                                       1933988509
pageCount                                                         592
shortDescription    "Flexible Rails created a standard to which I ...
authors                                             [Peter Armstrong]
categories                                          [Web Development]
Name: 10, dtype: object
11 title                                                   Hello! Flex 4
isbn                                                       1933988762
pageCount                                                         258
shortDescription    Hello! Flex 4 progresses through 26 self-conta...
authors                                             [Peter Armstrong]
categories                                                 [Internet]
Name: 11, dtype: object
12 title                                                     Coffeehouse
isbn                                                       1884777384
pageCount                                                         316
shortDescription    Coffeehouse is an anthology of stories, poems ...
authors                              [Levi Asher, Christian Crumlish]
categories                                            [Miscellaneous]
Name: 12, dtype: object
13 title               Team Foundation Server 2008 in Action
isbn                                           1933988592
pageCount                                             344
shortDescription                                      NaN
authors                                     [Jamil Azher]
categories                               [Microsoft .NET]
Name: 13, dtype: object
14 title                      Brownfield Application Development in .NET
isbn                                                       1933988711
pageCount                                                         550
shortDescription    Brownfield Application Development in .Net sho...
authors                                  [Kyle Baley, Donald Belcham]
categories                                                [Microsoft]
Name: 14, dtype: object
15 title                                               MongoDB in Action
isbn                                                       1935182870
pageCount                                                           0
shortDescription    MongoDB In Action is a comprehensive guide to ...
authors                                                 [Kyle Banker]
categories                                [Next Generation Databases]
Name: 15, dtype: object
16 title               Distributed Application Development with Power...
isbn                                                       1884777686
pageCount                                                         504
shortDescription                                                  NaN
authors                                         [Michael J. Barlotta]
categories                                             [PowerBuilder]
Name: 16, dtype: object
17 title                          Jaguar Development with PowerBuilder 7
isbn                                                       1884777864
pageCount                                                         550
shortDescription    Jaguar Development with PowerBuilder 7 is the ...
authors                                            [Michael Barlotta]
categories                              [PowerBuilder, Client-Server]
Name: 17, dtype: object
18 title                                       Taming Jaguar
isbn                                           1884777686
pageCount                                             362
shortDescription                                      NaN
authors             [Michael J. Barlotta, Jason R. Weiss]
categories                                 [PowerBuilder]
Name: 18, dtype: object
19 title               3D User Interfaces with Java 3D
isbn                                     1884777902
pageCount                                       520
shortDescription                                NaN
authors                           [Jon Barrilleaux]
categories                [Java, Computer Graphics]
Name: 19, dtype: object
20 title                                             Hibernate in Action
isbn                                                       193239415X
pageCount                                                         400
shortDescription    "2005 Best Java Book!" -- Java Developer's Jou...
authors                                 [Christian Bauer, Gavin King]
categories                                                     [Java]
Name: 20, dtype: object
21 title               Hibernate in Action (Chinese Edition)
isbn                                                  NaN
pageCount                                             400
shortDescription                                      NaN
authors                     [Christian Bauer, Gavin King]
categories                                         [Java]
Name: 21, dtype: object
22 title                                 Java Persistence with Hibernate
isbn                                                       1932394885
pageCount                                                         880
shortDescription    "...this book is the ultimate solution. If you...
authors                                 [Christian Bauer, Gavin King]
categories                                                     [Java]
Name: 22, dtype: object
23 title               JSTL in Action
isbn                    1930110529
pageCount                      480
shortDescription               NaN
authors             [Shawn Bayern]
categories              [Internet]
Name: 23, dtype: object
24 title                                                iBATIS in Action
isbn                                                       1932394826
pageCount                                                         384
shortDescription       Gets new users going and gives experienced ...
authors                [Clinton Begin, Brandon Goodin, Larry Meadors]
categories                                          [Web Development]
Name: 24, dtype: object
25 title                                         Designing Hard Software
isbn                                                        133046192
pageCount                                                         350
shortDescription    "This book is well written ... The author does...
authors                                          [Douglas W. Bennett]
categories                           [Object-Oriented Programming, S]
Name: 25, dtype: object
26 title                                      Hibernate Search in Action
isbn                                                       1933988649
pageCount                                                         488
shortDescription    "A great resource for true database independen...
authors                              [Emmanuel Bernard, John Griffin]
categories                                                     [Java]
Name: 26, dtype: object
27 title                                                jQuery in Action
isbn                                                       1933988355
pageCount                                                         376
shortDescription    "The best-thought-out and researched piece of ...
authors                                  [Bear Bibeault, Yehuda Katz]
categories                                          [Web Development]
Name: 27, dtype: object
28 title                                jQuery in Action, Second Edition
isbn                                                       1935182323
pageCount                                                         488
shortDescription    jQuery in Action, Second Edition is a fast-pac...
authors                                  [Bear Bibeault, Yehuda Katz]
categories                                                     [Java]
Name: 28, dtype: object
29 title               Building Secure and Reliable Network Applications
isbn                                                       1884777295
pageCount                                                         591
shortDescription    "... tackles the difficult problem of building...
authors                                           [Kenneth P. Birman]
categories                                       [Networking, Theory]
Name: 29, dtype: object
30 title                                                  Ruby for Rails
isbn                                                       1932394699
pageCount                                                         532
shortDescription    The word is out: with Ruby on Rails you can bu...
authors                                              [David A. Black]
categories                                          [Web Development]
Name: 30, dtype: object
31 title                                       The Well-Grounded Rubyist
isbn                                                       1933988657
pageCount                                                         520
shortDescription    What would appear to be the most complex topic...
authors                                              [David A. Black]
categories                                              [Programming]
Name: 31, dtype: object
32 title                                          Website Owner's Manual
isbn                                                       1933988452
pageCount                                                         296
shortDescription    Website Owner's Manual helps you form a vision...
authors                                                [Paul A. Boag]
categories                                                 [Internet]
Name: 32, dtype: object
33 title                                         ASP.NET 4.0 in Practice
isbn                                                       1935182463
pageCount                                                         504
shortDescription    ASP.NET 4.0 in Practice contains real world te...
authors             [Daniele Bochicchio, Stefano Mostarda, , Marco...
categories                                           [Microsoft .NET]
Name: 33, dtype: object
34 title                                                   Hello! Python
isbn                                                       1935182080
pageCount                                                         350
shortDescription    Hello! Python fully covers the building blocks...
authors                                              [Anthony Briggs]
categories                                                   [Python]
Name: 34, dtype: object
35 title               PFC Programmer's Reference Manual
isbn                                       1884777554
pageCount                                         368
shortDescription                                  NaN
authors                              [Richard Brooks]
categories                             [PowerBuilder]
Name: 35, dtype: object
36 title                             Graphics File Formats
isbn                                          133034054
pageCount                                           484
shortDescription                                    NaN
authors             [C. Wayne Brown, Barry J. Shepherd]
categories                          [Computer Graphics]
Name: 36, dtype: object
37 title                              Visual Object Oriented Programming
isbn                                                        131723979
pageCount                                                         280
shortDescription                                                  NaN
authors             [Margaret M. Burnett, Adele Goldberg, , Ted G....
categories                                              [Programming]
Name: 37, dtype: object
38 title                   iOS in Practice
isbn                         1617291269
pageCount                           325
shortDescription                    NaN
authors                [Bear P. Cahill]
categories          [Mobile Technology]
Name: 38, dtype: object
39 title                                                iPhone in Action
isbn                                                       193398886X
pageCount                                                         472
shortDescription       There is not another iPhone title that does...
authors                       [Christopher Allen, Shannon Appelcline]
categories                                          [Web Development]
Name: 39, dtype: object
40 title                                         Silverlight 2 in Action
isbn                                                       1933988428
pageCount                                                         400
shortDescription       Silverlight 2 in Action gives you a solid, ...
authors                             [Chad A. Campbell, John Stockton]
categories                                           [Microsoft .NET]
Name: 40, dtype: object
41 title                           The Quick Python Book, Second Edition
isbn                                                       193518220X
pageCount                                                         360
shortDescription    This revision of Manning's popular The Quick P...
authors                                              [Naomi R. Ceder]
categories                                                   [Python]
Name: 41, dtype: object
42 title               Internet and Intranet Applications with PowerB...
isbn                                                       1884777600
pageCount                                                         390
shortDescription                                                  NaN
authors                                                [Tom Cervenka]
categories                                             [PowerBuilder]
Name: 42, dtype: object
43 title                    Practical Methods for Your Year 2000 Problem
isbn                                                       188477752X
pageCount                                                         236
shortDescription    Practical Methods for Your Year 2000 Problem g...
authors                                              [Robert Chapman]
categories                                                 [Business]
Name: 43, dtype: object
44 title                                                   Mobile Agents
isbn                                                       1884777368
pageCount                                                         320
shortDescription    Mobile Agents is the first book to give the re...
authors               [William R. Cockayne and Michael Zyda, editors]
categories                                                 [Internet]
Name: 44, dtype: object
45 title                                Spring Dynamic Modules in Action
isbn                                                       1935182307
pageCount                                                         450
shortDescription    Spring Dynamic Modules in Action introduces Sp...
authors             [Arnaud Cogoluegnes, Thierry Templier, , Andy ...
categories                                                     [Java]
Name: 45, dtype: object
46 title               SQL Server 2008 Administration in Action
isbn                                              193398872X
pageCount                                                468
shortDescription                                         NaN
authors                                       [Rod Colledge]
categories                                       [Microsoft]
Name: 46, dtype: object
47 title                                             Android in Practice
isbn                                                       1935182927
pageCount                                                         500