# Ein Datensatz mit Büchern

## Einlesen der Daten

In [19]:
import pandas as pd

df = pd.read_json('https://raw.githubusercontent.com/ozlerhakan/mongodb-json-files/master/datasets/books.json', lines=True)
df.set_index('_id', inplace=True)
df.drop(['publishedDate', 'longDescription', 'status', 'thumbnailUrl'], inplace=True, axis=1)
df.head()

,title,isbn,pageCount,shortDescription,authors,categories
_id,,,,,,
1,Unlocking Android,1933988673,416,Unlocking Android: A Developer's Guide provide...,"[W. Frank Ableson, Charlie Collins, Robi Sen]","[Open Source, Mobile]"
2,"Android in Action, Second Edition",1935182722,592,"Android in Action, Second Edition is a compreh...","[W. Frank Ableson, Robi Sen]",[Java]
3,Specification by Example,1617290084,0,NaN,[Gojko Adzic],[Software Engineering]
4,Flex 3 in Action,1933988746,576,NaN,"[Tariq Ahmed with Jon Hirschi, Faisal Abid]",[Internet]
5,Flex 4 in Action,1935182420,600,NaN,"[Tariq Ahmed, Dan Orlando, John C. Bland II, J...",[Internet]

* Hinweis
  * Die JSON-Datei enthält Book-Objekte zeilenweise, nicht in Form einer Liste
  * Deshalb ist beim Einlesen der Parameter lines=True zu setzen

## Beschreibung

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 431 entries, 1 to {'$oid': '53c2ae8528d75d572c06adbc'}
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             431 non-null    object
 1   isbn              428 non-null    object
 2   pageCount         431 non-null    int64
 3   shortDescription  160 non-null    object
 4   authors           431 non-null    object
 5   categories        431 non-null    object
dtypes: int64(1), object(5)
memory usage: 23.6+ KB

In [21]:
df.describe()

         pageCount
count   431.000000
mean    289.259861
std     260.873349
min       0.000000
25%       0.000000
50%     350.000000
75%     475.000000
max    1101.000000

## Dicke Bücher, die mehr als 800 Seiten haben

In [22]:
df[df['pageCount'] > 800]

,title,isbn,pageCount,shortDescription,authors,categories
_id,,,,,,
24,Java Persistence with Hibernate,1932394885,880,"""...this book is the ultimate solution. If you...","[Christian Bauer, Gavin King]",[Java]
70,Essential Guide to Peoplesoft Development and ...,1884777929,1101,NaN,"[Tony DeLia, Galina Landres, Isidor Rivera, Pr...",[Client-Server]
79,Java Foundation Classes,1884777678,1088,NaN,"[Stephen C. Drye, William C. Wake]",[Java]
153,"Java Network Programming, Second Edition",188477749X,860,NaN,"[Merlin Hughes, Michael Shoffner, , Derek Hamner]",[Java]
180,The Awesome Power of Direct3D/DirectX,1884777473,840,The Awesome Power of Direct3D/DirectX shows yo...,[Peter J. Kovach],[Computer Graphics]
230,SQL Server MVP Deep Dives,1935182048,848,SQL Server MVP Deep Dives is organized into fi...,"[Contributions from 53 SQL Server MVPs, Edited...",[Microsoft .NET]
231,SQL Server MVP Deep Dives,9781935182047,848,SQL Server MVP Deep Dives is organized into fi...,[Contributions from 53 SQL Server MVPs; Edited...,[Microsoft .NET]
232,SQL Server MVP Deep Dives,9781935182047,848,NaN,"[Paul Nielsen, Kalen Delaney, Greg Low, Adam M...",[Microsoft .NET]
249,Silverlight 5 in Action,1617290319,925,NaN,[Pete Brown],"[Microsoft, .NET]"
272,Swing Second Edition,193011088X,912,NaN,[],"[Java, Internet]"
315,Ten Years of UserFriendly.Org,1935182129,1096,This unique collector's volume includes every ...,"[JD ""Illiad"" Frazer]",[Miscellaneous]
{'$oid': '53c2ae8528d75d572c06ad9f'},Windows Forms in Action,1932394656,950,NaN,[],[]
{'$oid': '53c2ae8528d75d572c06adaa'},Dynamic WAP Application Development,1930110081,888,NaN,[],[]

## Die 25% der seitenstärksten Bücher

In [23]:
quantile_75 = df['pageCount'].quantile(0.75)
df[df['pageCount'] > quantile_75]

,title,isbn,pageCount,shortDescription,authors,categories
_id,,,,,,
2,"Android in Action, Second Edition",1935182722,592,"Android in Action, Second Edition is a compreh...","[W. Frank Ableson, Robi Sen]",[Java]
4,Flex 3 in Action,1933988746,576,NaN,"[Tariq Ahmed with Jon Hirschi, Faisal Abid]",[Internet]
5,Flex 4 in Action,1935182420,600,NaN,"[Tariq Ahmed, Dan Orlando, John C. Bland II, J...",[Internet]
11,Flexible Rails,1933988509,592,"""Flexible Rails created a standard to which I ...",[Peter Armstrong],[Web Development]
16,Brownfield Application Development in .NET,1933988711,550,Brownfield Application Development in .Net sho...,"[Kyle Baley, Donald Belcham]",[Microsoft]
...,...,...,...,...,...,...
{'$oid': '53c2ae8528d75d572c06adab'},IronPython in Action,1933988339,496,NaN,[],[]
{'$oid': '53c2ae8528d75d572c06adac'},Art of Java Web Development,1932394060,624,NaN,[],[]
{'$oid': '53c2ae8528d75d572c06adaf'},Struts Recipes,1932394249,520,NaN,[],[]
{'$oid': '53c2ae8528d75d572c06adb1'},Jess in Action,1930110898,480,Jess in Action first introduces rule programmi...,[],[]
{'$oid': '53c2ae8528d75d572c06adb5'},ASP.NET AJAX in Action,1933988142,570,NaN,[],[]