# Die Pandas Bibliothek

## Installation

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\raine\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

* Hinweis
    * Installiert wird hier auch `numpy`
        * Numpy liefert uns intern einen Satz hocheffizienter Collections, die von Pandas benutzt werden
        * Direkt Bezug zu Numpy ist selten, aber durchaus möglich

## Import der notwendigen Bibliotheken

In [3]:
import pandas as pd
import numpy as np

## Laden des Datensatzes

In [4]:
pd.read_csv('diamonds.csv')

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...,...
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

* Hinweis
    * Die Reader-Methoden sind prinzipiell allesamt netzwerkfähig

In [5]:
pd.read_json('http://javacream.eu:8080/people')

   id    lastname  firstname gender  height
0   1    Sawitzki     Rainer      m     183
1   2       Meier       Hans      m     163
2   3     Metzger      Georg      m     190
3   4     Metzger     Frieda      f     167
4   5    Hoffmann      Hanna      f     155
5   6  Pausenkurt     Pascal      m     177
6   7       Fisch      Wanda      f     164
7   8     Ziegler     Thomas      m     193
8   9        Tost  Franziska      f     177
9  10      Berger       Hans      m     183

*  
  * Spezialfall: Datenzugriff

In [6]:
import sqlite3
connection = sqlite3.connect('books.db')
pd.read_sql('select * from books', connection)

               isbn            title  price  pages
0     1216387044038     Book Title 1  22.82    828
1     8414458827277     Book Title 2   8.11    322
2     0403824736292     Book Title 3  62.34    228
3     1562090389834     Book Title 4  73.85    124
4     0538802272213     Book Title 5  47.08     69
...             ...              ...    ...    ...
1995  0560636261378   Book Title 996  55.66    410
1996  9856114419795   Book Title 997  26.07    784
1997  0884711675089   Book Title 998  16.50   1142
1998  9716067226377   Book Title 999  27.58     54
1999  0249901319330  Book Title 1000  19.29    981

[2000 rows x 4 columns]