# Die Pandas Bibliothek

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## Lese-Methoden

### Lesen einer lokalen CSV-Datei

In [4]:
df = pd.read_csv('people.csv')
df.head()

               Name  Weight  Height
0      Anna Neumann    55.8   165.0
1        Ben Wagner    78.6   180.0
2       Carla Weber    60.5     NaN
3     David Schmidt    85.5   185.0
4  Elena Zimmermann    52.5   160.0

### Lesen einer lokalen JSON-Datei

In [5]:
df = pd.read_json('people.json')
df.head()

   id  lastname firstname gender  height
0   1  Sawitzki    Rainer      m     183
1   2     Meier      Hans      m     163
2   3   Metzger     Georg      m     190
3   4   Metzger    Frieda      f     167
4   5  Hoffmann     Hanna      f     155

### Lesen eines RESTful WebServices

In [6]:
df = pd.read_json('http://javacream.eu:8080/people')
df.head()

   id  lastname firstname gender  height
0   1  Sawitzki    Rainer      m     183
1   2     Meier      Hans      m     163
2   3   Metzger     Georg      m     190
3   4   Metzger    Frieda      f     167
4   5  Hoffmann     Hanna      f     155

### Lesen einer CSV-Datei vom Internet

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/lawlesst/vivo-sample-data/refs/heads/master/data/csv/people.csv')
df.head()

,person_ID,name,first,last,middle,email,phone,fax,title
0,3130,"Burks, Rosella",Rosella,Burks,NaN,BurksR@univ.edu,963.555.1253,963.777.4065,Professor
1,3297,"Avila, Damien",Damien,Avila,NaN,AvilaD@univ.edu,963.555.1352,963.777.7914,Professor
2,3547,"Olsen, Robin",Robin,Olsen,NaN,OlsenR@univ.edu,963.555.1378,963.777.9262,Assistant Professor
3,1538,"Moises, Edgar Estes",Edgar,Moises,Estes,MoisesE@univ.edu,963.555.2731x3565,963.777.8264,Professor
4,2941,"Brian, Heath Pruitt",Heath,Brian,Pruitt,BrianH@univ.edu,963.555.2800,963.777.7249,Associate Curator

### Lesen von Daten aus einer Datenbank

In [10]:
import mysql.connector

connection = mysql.connector.connect(
    host='javacream.eu', port=3406, username='user', password='user', database='javacream'
)

df = pd.read_sql('select * from PEOPLE', connection)
df.head()

C:\Users\raine\AppData\Local\Temp\ipykernel_8684\382096201.py:7: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql('select * from PEOPLE', connection)

   id firstname lastname  height  weight
0   1    Stacey   Miller    1.68    92.0
1   2     Carla   Gentry    1.68    85.4
2   3      Emma  Harding    1.75    98.2
3   4  Jeanette    Lopez    1.58    73.8
4   5    Edward    White    1.63    68.5