
# Analyse des Diamanten-Datensatzes

## Installation der notwendigen Bibliotheken

* Einmalige Installation mit pip

In [6]:
pip install pandas
python -m pip install pandas
pip install matplotlib
python -m pip install matplotlib

SyntaxError: invalid syntax (2883240124.py, line 1)

## Notwendige Imports

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

* Die numpy-Bibliothek ist eine Umsetzung von Collections, die im  Vergleich zu den Standard-Collections deutlich optimiert sind

## Einladen des Datensatzes

In [12]:
df = pd.read_csv('diamonds.csv')

* df ist ein Pandas DataFrame
* Eine spezielle Collection mit komplexem internen Aufbau

## Daten Exploration

In [ ]:
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,x0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [ ]:
df.tail()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
53935,53936,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,53937,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,53938,0.7,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,53939,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,53940,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  53940 non-null  int64
 1   carat       53940 non-null  object
 2   cut         53940 non-null  object
 3   color       53940 non-null  object
 4   clarity     53940 non-null  object
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 4.5+ MB